### ISSUE TITLE
Set-HostsEntry occasionally nuking all host entries

### ISSUE THREAD

**Issue by jcoutch** [webmd-health-services/Carbon#39] opened 2018-01-16 16:27 UTC
Occasionally, when running Set-HostsEntry, I'll get an error about not being able to access the hosts file because another process has it locked.  If I wait about 10-15 seconds and check the hosts file, all of my entries are gone.

I've had this happen a few times, but can't reproduce it consistently.  It seems to happen when there are multiple calls to Set-HostsEntry in succession.  But when it does happen, it's extremely annoying.

**Comment by splatteredbits** [comment] 2018-01-16 21:08
What version of Carbon? The current version of Set-HostsEntry tries to handle this situation.

**Comment by jcoutch** [comment] 2018-01-16 21:15
2.5.0 (installed from Chocolatey.)

**Comment by jcoutch** [comment] 2018-01-31 19:08
Just had Set-HostsEntry nuke my hosts file again.  Here's a screenshot of the exception, as well as the output of `choco list carbon -lo` (to show I'm on 2.5.0):

![image](https://user-images.githubusercontent.com/386545/35642020-d715255a-068f-11e8-9437-de51444b2cf4.png)

**Comment by jcoutch** [comment] 2018-01-31 21:07
Had the error occur again...and got some more details.  When running `cat c:\windows\system32\drivers\etc\hosts` within the same PowerShell window, it states that another process currently has the hosts file locked.  It's only when I close the PowerShell window that the file is nuked.  My thought is something in Set-HostsEntry is holding the file open until the PowerShell session is terminated.

**Comment by jcoutch** [comment] 2018-01-31 21:38
I created a script that reproduces the issue:
    $ErrorActionPreference = "Stop"

    for($i = 0; $i -lt 100; $i++) {
        $domain = "somedomain-$i.site.local"
    
        Write-Host "Adding $domain to hosts file"
        Set-HostsEntry "127.0.0.1" $domain
    }

On my machine, this script usually throws an error before `$I` reaches 7.  I'm running Windows 10 Fall Creators update, IIS is installed, and here is my `$PSVersionTable` variable:

    Name                           Value
    ----                           -----
    PSVersion                      5.1.16299.98
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.16299.98
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1

**Comment by dabitbol** [comment] 2018-11-13 20:19
We are having the same issue. Any updates?

**Comment by AndrewSav** [comment] 2018-11-14 05:00
incidentally I cannot reproduce that with @jcoutch 's script.

**Comment by splatteredbits** [comment] 2018-11-27 01:08
I'm unable to reproduce this on Windows 7 or Windows 2012 R2. I don't have access to a Windows 10 computer.

Can you use [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to find out what processes are accessing the hosts file? I suspect this might be related to your virus scanning tool.

**Comment by splatteredbits** [comment] 2018-11-27 01:09
Also, if you could paste a script stack trace from the error, that would be great:  `$Error[0].ScriptStackTrace`. That will tell me exactly where the error is in Carbon. PowerShell doesn't give very helpful script locations when errors happen.

**Comment by jcoutch** [comment] 2019-02-19 16:59
@splatteredbits - I had this happen again today, so I tried a few things out.

I ran the reproduction script above along with Process Monitor, and filtered to only events on the hosts file.  I did notice Windows Defender was scanning the file on every write, so I temporarily added an exclusion for the hosts file and re-ran the test.  While it seemed like the issue was fixed, and I no longer saw Defender in the Process Monitor output, I increased the count to 1000 in the reproduction script, and managed to get the error again.

In both cases (with and without the hosts file being excluded), the last process to touch the hosts file was the Network Service:
```
C:\Windows\system32\svchost.exe -k NetworkService -p -s Dnscache
```

So, it appears that it's the core network service that pulls the lock on the file, making the stream non-readable.

Also, `$Error[0].ScriptStackTrace` returned nothing (since the first error was a message about the script stopping because of my `ErrorActionPreference` setting), but here is the response from `$Error[1].ScriptStackTrace`:
```
PS C:\test> $Error[1].ScriptStackTrace
at Write-File<End>, C:\Program Files\WindowsPowerShell\Modules\Carbon\Functions\Write-File.ps1: line 116
at Set-HostsEntry, C:\Program Files\WindowsPowerShell\Modules\Carbon\Functions\Set-HostsEntry.ps1: line 176
at <ScriptBlock>, C:\test\carbon-reproduce.ps1: line 7
at <ScriptBlock>, <No file>: line 1
```

**Comment by jcoutch** [comment] 2019-02-19 17:05
Oh, if you need a Windows 10 VM to test with, Microsoft has dev VM's available with evaluation licenses of Windows 10:
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

Or you can sign up for Visual Studio Dev Essentials, which will give you $200 worth of Azure credits for the first month (so you can spin up a VM in Azure):
https://visualstudio.microsoft.com/dev-essentials/

**Comment by splatteredbits** [comment] 2019-09-16 21:45
Fixed in Carbon 2.9.0-rc587, now available on the [PowerShell Gallery](https://www.powershellgallery.com/packages/Carbon/2.9.0-rc587) and [GitHub](https://github.com/webmd-health-services/Carbon/releases/tag/2.9.0-rc587). Please take a  few minutes to download and test that your issue is fixed. We'll be publishing the final version of 2.9.0 Wednesday or Thursday.

**Comment by jcoutch** [comment] 2019-09-17 02:11
@splatteredbits - Just tried 2.9.0-rc587...and it looks like it's working!  Are you planning on releasing 2.9.0 on Chocolatey as well?

**Comment by splatteredbits** [comment] 2019-09-17 18:37
Yes. 2.9.0 will be released on all the usual platforms (Gallery, GitHub, Chocolatey, and NuGet).

**Comment by splatteredbits** [comment] 2019-09-19 20:06
2.9.0 is out.

**Closed by splatteredbits** 2019-09-19 20:06 UTC
Labels: community
